version: '3.8'

services:

  db:
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_6:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"

volumes:
  postgres_data_6:
